name: "Build & Release"

on:
  push:
    branches:
      - main

jobs:
  run-ci:
    uses: ./.github/workflows/ci.yml
    secrets: inherit

  release-please:
    runs-on: ubuntu-latest
    needs: run-ci
    permissions:
      contents: write
      pull-requests: write
      issues: write
    steps:
      - uses: googleapis/release-please-action@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
